# Generated by Django 3.2.5 on 2021-07-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_phone', models.CharField(max_length=20)),
                ('acc_type', models.CharField(max_length=80)),
                ('acc_strength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('ct_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ct_name', models.CharField(max_length=50)),
                ('ct_email', models.EmailField(max_length=254)),
                ('ct_dept', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_username', models.EmailField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
            ],
        ),
    ]
